
const DEFAULTS={latitude:43.793931,longitude:4.014810,surface:8,flow:8,kc:.9,rainEfficiency:.8,lastWatering:localDateString(new Date())};
const STORAGE_KEY="monPotagerSettingsV1";let weatherRows=[];
document.addEventListener("DOMContentLoaded",()=>{bindEvents();loadSettingsIntoForm();refresh();registerServiceWorker()});
function bindEvents(){document.querySelector("#refreshButton").addEventListener("click",refresh);document.querySelector("#wateredButton").addEventListener("click",markWatered);document.querySelector("#settingsForm").addEventListener("submit",saveSettings)}
function settings(){try{return{...DEFAULTS,...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}}catch{return{...DEFAULTS}}}
function persistSettings(v){localStorage.setItem(STORAGE_KEY,JSON.stringify(v))}
function loadSettingsIntoForm(){const s=settings();["surface","flow","kc","rainEfficiency","lastWatering"].forEach(id=>document.querySelector("#"+id).value=s[id])}
async function refresh(){setLoading(true);hideError();try{const s=settings(),vars=["et0_fao_evapotranspiration","precipitation_sum","temperature_2m_min","temperature_2m_max"].join(","),url=new URL("https://api.open-meteo.com/v1/forecast");url.search=new URLSearchParams({latitude:s.latitude,longitude:s.longitude,daily:vars,timezone:"Europe/Paris",past_days:"15",forecast_days:"16"});const r=await fetch(url);if(!r.ok)throw new Error(`Open-Meteo répond ${r.status}.`);const d=await r.json();if(!d.daily?.time)throw new Error("Données météo absentes.");weatherRows=d.daily.time.map((date,i)=>({date,etp:num(d.daily.et0_fao_evapotranspiration[i]),rain:num(d.daily.precipitation_sum[i]),tmin:num(d.daily.temperature_2m_min[i]),tmax:num(d.daily.temperature_2m_max[i])}));render()}catch(e){showError("Impossible d’actualiser la météo. "+e.message)}finally{setLoading(false)}}
function render(){const s=settings(),today=localDateString(new Date()),period=weatherRows.filter(r=>r.date>s.lastWatering&&r.date<=today),etp=sum(period.map(r=>r.etp)),rain=sum(period.map(r=>r.rain)),etc=etp*num(s.kc),effective=rain*num(s.rainEfficiency),dose=Math.max(0,etc-effective),volume=dose*num(s.surface),minutes=num(s.flow)>0?volume/num(s.flow):0;let advice="Pas besoin d’arroser";if(dose>.1&&dose<4)advice="Arrosage léger";if(dose>=4&&dose<8)advice="Arroser aujourd’hui";if(dose>=8)advice="Arrosage important";txt("#advice",advice);txt("#volume",`${round(volume,1)} L`);txt("#duration",formatMinutes(minutes));txt("#etpTotal",`${round(etp,2)} mm`);txt("#rainTotal",`${round(rain,2)} mm`);txt("#dose",`${round(dose,2)} mm`);const t=new Date();t.setDate(t.getDate()+1);const tr=weatherRows.find(r=>r.date===localDateString(t));txt("#rainTomorrow",`${round(tr?.rain||0,1)} mm`);txt("#lastWateringText",`Dernier arrosage : ${formatDate(s.lastWatering)}`);txt("#updatedAt",`Mis à jour à ${new Date().toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit"})}`);renderForecast(today)}
function renderForecast(today){const c=document.querySelector("#forecast");c.innerHTML="";weatherRows.filter(r=>r.date>=today).slice(0,7).forEach(r=>{const e=document.createElement("div");e.className="forecast-row";e.innerHTML=`<strong>${dayLabel(r.date)}</strong><span>ETP ${round(r.etp,1)}</span><span>🌧 ${round(r.rain,1)}</span><span>${round(r.tmin,0)}° / ${round(r.tmax,0)}°</span>`;c.appendChild(e)})}
function markWatered(){const s=settings();s.lastWatering=localDateString(new Date());persistSettings(s);loadSettingsIntoForm();render()}
function saveSettings(e){e.preventDefault();const s=settings(),n={...s,surface:num(val("surface")),flow:num(val("flow")),kc:num(val("kc")),rainEfficiency:num(val("rainEfficiency")),lastWatering:val("lastWatering")};persistSettings(n);render()}
function registerServiceWorker(){if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(console.error)}
function setLoading(v){const b=document.querySelector("#refreshButton");b.disabled=v;b.textContent=v?"…":"↻"}
function showError(m){const e=document.querySelector("#errorMessage");e.textContent=m;e.hidden=false}function hideError(){document.querySelector("#errorMessage").hidden=true}
function txt(s,v){document.querySelector(s).textContent=v}function val(id){return document.querySelector("#"+id).value}
function num(v){const n=Number(v);return Number.isFinite(n)?n:0}function sum(v){return v.reduce((a,b)=>a+num(b),0)}
function round(v,d){const f=10**d;return Math.round((num(v)+Number.EPSILON)*f)/f}
function formatMinutes(v){const s=Math.round(num(v)*60),m=Math.floor(s/60),r=s%60;return`${m} min ${String(r).padStart(2,"0")} s`}
function localDateString(date){const p=new Intl.DateTimeFormat("fr-CA",{timeZone:"Europe/Paris",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(date),m=Object.fromEntries(p.map(x=>[x.type,x.value]));return`${m.year}-${m.month}-${m.day}`}
function formatDate(s){return new Date(s+"T12:00:00").toLocaleDateString("fr-FR",{day:"numeric",month:"long",year:"numeric"})}
function dayLabel(s){const d=new Date(s+"T12:00:00"),today=localDateString(new Date()),t=new Date();t.setDate(t.getDate()+1);if(s===today)return"Aujourd’hui";if(s===localDateString(t))return"Demain";return d.toLocaleDateString("fr-FR",{weekday:"short",day:"numeric",month:"short"})}
